# Update file
name: update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install dependencies 
        run: pip install jupyter lxml pandas requests openpyxl datawrapper==0.6.0 datetime requests numpy
      - name: Execute notebook    
        env: 
          dw_secret: ${{ secrets.DATAWRAPPER }}  
        run: jupyter nbconvert --to notebook --execute "entwicklung-der-energiewende/TestGitHub (2).ipynb" --stdout
      - name: Execute notebook    
        env: 
          dw_secret: ${{ secrets.DATAWRAPPER }}  
        run: jupyter nbconvert --to notebook --execute "entwicklung-der-energiewende/Mobilität_Datenseite.ipynb" --stdout        
