# Update file
name: update
permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
    - name: Install Python packages
      run: pip install jupyter lxml pandas requests openpyxl datawrapper datetime numpy
    - name: Run Python notebook (Energiepreise)
      run: jupyter nbconvert --to notebook --execute "2504-Preise/energiepreise.ipynb" --stdout
    - name: Run Python notebook (Abwärme)
      env: 
        dw_secret: ${{ secrets.DATAWRAPPER }}
      run: jupyter nbconvert --to notebook --execute "waste-heat/Abwärme_Analyse_Kurz.ipynb" --stdout
    - name: Run Python notebook (Entwicklung der Energiewende)
      env:
        dw_secret: ${{ secrets.DATAWRAPPER }}
      run: jupyter nbconvert --to notebook --execute "entwicklung-der-energiewende/stand_ew_github_test.ipynb" --stdout
    - name: Run R script (Energiepreise in R)
      run: Rscript "R/energiepreise.R"
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
